### ISSUE TITLE
Probleme to compile on 5.1.5 kernel 

### ISSUE THREAD

**Issue by Thava-P** [lwfinger/rtl8192du#76] opened 2019-05-31 09:16 UTC
[thava@Cerise rtl8192du-master]$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.1.5-arch1-2-ARCH/build M=/home/thava/Téléchargements/rtl8192du-master  modules
make[1] : on entre dans le répertoire « /usr/lib/modules/5.1.5-arch1-2-ARCH/build »
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_cmd.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_security.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_debug.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_io.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_ioctl_query.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_ioctl_set.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_ieee80211.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_mlme.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_mlme_ext.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_wlan_util.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_pwrctrl.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_rf.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_recv.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_sta_mgt.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_ap.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_xmit.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_p2p.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_tdls.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_br_ext.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_iol.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_sreset.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/core/rtw_efuse.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/hal_intf.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/hal_com.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/dm.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/usb_ops_linux.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_hal_init.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_phycfg.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_rf6052.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_dm.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_rxdesc.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_cmd.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/usb_halinit.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192du_led.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192du_xmit.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192du_recv.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/rtl8192d_xmit.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/hal/Hal8192DUHWImg.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/os_dep/osdep_service.o
  CC [M]  /home/thava/Téléchargements/rtl8192du-master/os_dep/os_intfs.o
/home/thava/Téléchargements/rtl8192du-master/os_dep/os_intfs.c:577:22: error: initialisation de « u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)) » {alias « short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)) »} depuis le type pointeur « u16 (*)(struct net_device *, struct sk_buff *, struct net_device *) » {alias « short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *) »} qui est incompatible [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/home/thava/Téléchargements/rtl8192du-master/os_dep/os_intfs.c:577:22: note: (près de l'initialisation de « rtw_netdev_ops.ndo_select_queue »)
/home/thava/Téléchargements/rtl8192du-master/os_dep/os_intfs.c:1713:22: error: initialisation de « u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)) » {alias « short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)) »} depuis le type pointeur « u16 (*)(struct net_device *, struct sk_buff *, struct net_device *) » {alias « short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *) »} qui est incompatible [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,
                      ^~~~~~~~~~~~~~~~
/home/thava/Téléchargements/rtl8192du-master/os_dep/os_intfs.c:1713:22: note: (près de l'initialisation de « rtw_netdev_if2_ops.ndo_select_queue »)
cc1 : certains avertissements sont traités comme des erreurs
make[2]: *** [scripts/Makefile.build:276: /home/thava/Téléchargements/rtl8192du-master/os_dep/os_intfs.o] Error 1
make[1]: *** [Makefile:1571: _module_/home/thava/Téléchargements/rtl8192du-master] Error 2
make[1] : on quitte le répertoire « /usr/lib/modules/5.1.5-arch1-2-ARCH/build »
make: *** [Makefile:609: modules] Error 2
[thava@Cerise rtl8192du-master]$

**Comment by Thava-P** [comment] 2019-05-31 09:18
And that not only 5.1.5(arch) is in Fedora 30 kernel (5.1.X) and 4.19 (ubuntu).
I tried these distro is doesn't working.

**Comment by lwfinger** [comment] 2019-05-31 16:49
When you have a problem with building, ALWAYS do a git pull before writing an issue. I fixed the issue on 22 May.

It appears that you downloaded the zip version of the repo. When you do that, you have to do a full download whenever anything is changed. If you get the source with
git pull https://GitHub.com/lwfinger/rtl8723du.git
then doing a 'git pull' gets you the changes with a minimum of effort.

**Comment by MilhouseVH** [comment] 2019-05-31 19:12
5503b4b4bac1d32abd17bb6b197a9c948f9e5202 seems to be the cause of the 5.1.y failure. which results in:

https://github.com/lwfinger/rtl8192du/blob/master/os_dep/os_intfs.c#L456-L458

If 5503b4b4bac1d32abd17bb6b197a9c948f9e5202 is dropped (http://ix.io/1KzO) then `master` will build successfully with 5.1.5.

**Comment by MilhouseVH** [comment] 2019-05-31 19:25
Actually it might be the merge 44444222fd4f3189bfe0c49419c070c7ba62822a commit rather than 5503b4b4bac1d32abd17bb6b197a9c948f9e5202, but either way one or both of them has introduced a duff commit on top of the original 5.2-rc1 fix (#75) which now breaks pre-5.2 kernels.

**Comment by lwfinger** [comment] 2019-05-31 19:37
I just pushed a fix.

**Comment by Thava-P** [comment] 2019-05-31 19:38
@lwfinger I do it many times is doesn't work

**Closed by lwfinger** 2019-05-31 19:37 UTC

**Comment by lwfinger** [comment] 2019-05-31 21:10
Did you do a 'git pull' in the last two hours?

**Comment by Thava-P** [comment] 2019-05-31 21:13
@lwfinger no I Wil try tomorrow

**Comment by Thava-P** [comment] 2019-06-01 08:54
> Did you do a 'git pull' in the last two hours?

Thanks , that's work .
